{"version":3,"sources":["file:///Users/apple/Documents/Dads/coco-poker/node_modules/axios/lib/cancel/CanceledError.js"],"names":["CanceledError","message","config","request","AxiosError","call","ERR_CANCELED","name","utils","inherits","__CANCEL__"],"mappings":"AAAA;;;;;;;AAKA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA;AACA,WAASA,aAAT,CAAuBC,OAAvB,EAAgCC,MAAhC,EAAwCC,OAAxC,EAAiD;AAC/C;AACAC,IAAAA,UAAU,CAACC,IAAX,CAAgB,IAAhB,EAAsBJ,OAAO,IAAI,IAAX,GAAkB,UAAlB,GAA+BA,OAArD,EAA8DG,UAAU,CAACE,YAAzE,EAAuFJ,MAAvF,EAA+FC,OAA/F;AACA,SAAKI,IAAL,GAAY,eAAZ;AACD;;;;AAhBMH,MAAAA,U;;AACAI,MAAAA,K;;;AAiBPA,MAAAA,KAAK,CAACC,QAAN,CAAeT,aAAf,EAA8BI,UAA9B,EAA0C;AACxCM,QAAAA,UAAU,EAAE;AAD4B,OAA1C;;yBAIeV,a","sourcesContent":["'use strict';\n\nimport AxiosError from '../core/AxiosError.js';\nimport utils from '../utils.js';\n\n/**\n * A `CanceledError` is an object that is thrown when an operation is canceled.\n *\n * @param {string=} message The message.\n * @param {Object=} config The config.\n * @param {Object=} request The request.\n *\n * @returns {CanceledError} The created error.\n */\nfunction CanceledError(message, config, request) {\n  // eslint-disable-next-line no-eq-null,eqeqeq\n  AxiosError.call(this, message == null ? 'canceled' : message, AxiosError.ERR_CANCELED, config, request);\n  this.name = 'CanceledError';\n}\n\nutils.inherits(CanceledError, AxiosError, {\n  __CANCEL__: true\n});\n\nexport default CanceledError;\n"]}